/**
 * Comprehensive list of BJJ submission techniques
 * Used as the single source of options for all belt submission dropdowns
 * Alphabetically sorted A-Z
 */
export const SUBMISSION_OPTIONS = [
  'Achilles Lock',
  'Achilles Slicer',
  'Americana',
  'Anaconda Choke',
  'Anaconda Roll Choke',
  'Aoki Lock',
  'Arm Triangle',
  'Arm-In Guillotine',
  'Armbar',
  'Back Triangle',
  'Backstep Knee Bar',
  'Banana Split',
  'Baratoplata',
  'Baseball Bat Choke',
  'Bicep Slicer',
  'Body Lock Crank',
  'Body Triangle Choke',
  'Bow and Arrow Choke',
  'Bow Tie Choke',
  'Brabo Choke',
  'Buggy Choke',
  'Bulldog Choke',
  'Calf Crush',
  'Calf Lock',
  'Calf Slicer',
  'Can Opener (Neck Crank)',
  'Canto Choke',
  'Chin Strap Choke',
  'Clock Choke',
  'Cobra Clutch',
  'Collar and Sleeve Choke',
  'Cow Catcher Guillotine',
  'Crab Ride Calf Slicer',
  'Crab Ride Knee Bar',
  'Cross Ankle Lock',
  'Cross Collar Choke',
  'Cross Leg Lock',
  'Cross Sleeve Choke',
  'Crucifix Armbar',
  'Crucifix Choke',
  'Crucifix Choke with Gi',
  'Crucifix Kimura',
  "D'Arce Choke",
  'Double Wing Choke',
  'Dragon Sleeper',
  'Electric Chair',
  'Estima Lock',
  'Ezekiel Choke',
  'Figure Four Toe Hold',
  'Foot Crush',
  'Front Headlock Choke',
  'Ghost Escape Choke',
  'Gogoplata',
  'Goth Lock',
  'Groin Stretch',
  'Guillotine Choke',
  'Guillotine Crank',
  'Hammerlock',
  'Hamstring Slicer',
  'Head and Arm Choke',
  'High Elbow Guillotine',
  'Indian Death Lock',
  'Inside Heel Hook',
  'Inside Sankaku Lock',
  'Inverted Triangle',
  'Japanese Necktie',
  'Kesa Gatame Choke',
  'Keylock',
  'Kimura',
  'Knee Bar',
  'Knee Crush',
  'Lapel Baseball Bat Choke',
  'Lapel Loop Choke',
  'Leg Americana',
  'Leg Triangle Lock',
  'Loop Choke',
  'Low Wrist Guillotine',
  'Marcelotine',
  'Mir Lock',
  'Modified Baseball Bat Choke',
  'Modified Kesa Choke',
  'Monoplata',
  "Mother's Milk",
  'Mounted Triangle',
  'Neck Tie Crank',
  'No-Gi Ezekiel',
  'North South Choke',
  'Omoplata',
  'Outside Heel Hook',
  'Outside Sankaku Lock',
  'Papercutter Choke',
  'Peruvian Necktie',
  'Power Half Crank',
  'Power Half Nelson',
  'Punch Choke',
  'Rear Naked Choke',
  'Reverse Armbar',
  'Reverse Crucifix Choke',
  'Reverse Estima Lock',
  'Reverse Gogoplata',
  'Reverse Heel Hook',
  'Reverse Kimura',
  'Reverse Kimura from Back',
  'Reverse Toe Hold',
  'Reverse Triangle',
  'Reverse Twister',
  'Rib Crush',
  'Scarf Hold Choke',
  'Scissor Armbar',
  'Scissor Lock',
  'Scissor Rib Lock',
  'Shin Lock',
  'Short Choke',
  'Short Rear Naked Choke',
  'Shoulder Crusher',
  'Shoulder Lock',
  'Single Wing Choke',
  'Sleeper Hold',
  'Sliding Lapel Choke',
  'Smother Choke',
  'Spine Lock',
  'Straight Ankle Lock',
  'Straight Armlock',
  'Straight Foot Lock',
  'Suloev Stretch',
  'Tarikoplata',
  'Teepee Choke',
  'Ten Finger Guillotine',
  'Texas Cloverleaf',
  'The Mikey Lock',
  'Toe Hold',
  'Triangle Choke',
  'Truck Twister',
  'Twister',
  'Twister Side Control',
  'Von Flue Choke',
  'Wrist Lock',
  'Z-Lock',
  '50/50 Straight Ankle Lock',
] as const;

export type SubmissionOption = typeof SUBMISSION_OPTIONS[number];
