/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const SessionTheme = IDL.Variant({
  'openMat' : IDL.Null,
  'takedowns_standup' : IDL.Null,
  'turtleGame' : IDL.Null,
  'transitionsScrambles' : IDL.Null,
  'submissions' : IDL.Null,
  'pinsControl' : IDL.Null,
  'backControl' : IDL.Null,
  'guardRetention' : IDL.Null,
  'escapes' : IDL.Null,
  'sweeps' : IDL.Null,
  'legLocks' : IDL.Null,
  'guardPassing' : IDL.Null,
  'guardSystems' : IDL.Null,
});
export const Technique = IDL.Record({
  'id' : IDL.Text,
  'typ' : IDL.Text,
  'thumbnail' : IDL.Opt(ExternalBlob),
  'link' : IDL.Text,
  'name' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'linkedSessions' : IDL.Vec(IDL.Text),
  'category' : SessionTheme,
});
export const Time = IDL.Int;
export const TrainingType = IDL.Variant({ 'gi' : IDL.Null, 'noGi' : IDL.Null });
export const TrainingSession = IDL.Record({
  'id' : IDL.Text,
  'duration' : IDL.Nat,
  'date' : Time,
  'moodRating' : IDL.Float64,
  'sessionTheme' : SessionTheme,
  'trainingType' : TrainingType,
  'rolls' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const TrainingHourRecord = IDL.Record({
  'hours' : IDL.Float64,
  'date' : IDL.Text,
});
export const GymInfo = IDL.Record({
  'name' : IDL.Text,
  'logoUrl' : IDL.Opt(IDL.Text),
  'location' : IDL.Text,
});
export const BeltLevel = IDL.Variant({
  'blue' : IDL.Null,
  'purple' : IDL.Null,
  'black' : IDL.Null,
  'brown' : IDL.Null,
  'white' : IDL.Null,
});
export const BeltProgress = IDL.Record({
  'belt' : BeltLevel,
  'imageUrl' : IDL.Text,
  'stripes' : IDL.Nat,
});
export const StreakAchievement = IDL.Record({
  'id' : IDL.Text,
  'endDate' : Time,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'streakLength' : IDL.Nat,
  'startDate' : Time,
});
export const CrossTrainingGoal = IDL.Record({
  'id' : IDL.Text,
  'completionDate' : IDL.Opt(Time),
  'name' : IDL.Text,
  'description' : IDL.Text,
  'progress' : IDL.Nat,
  'targetArea' : IDL.Text,
});
export const TrainingMilestone = IDL.Record({
  'id' : IDL.Text,
  'beltProgress' : IDL.Opt(BeltProgress),
  'achievedDate' : Time,
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const TrainingGoal = IDL.Record({
  'id' : IDL.Text,
  'completedRepetitions' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'deadline' : IDL.Opt(Time),
  'creationDate' : Time,
  'targetRepetitions' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'gym' : IDL.Opt(GymInfo),
  'beltProgress' : BeltProgress,
  'nickname' : IDL.Text,
  'username' : IDL.Text,
  'streakAchievements' : IDL.Vec(StreakAchievement),
  'crossTrainingGoals' : IDL.Vec(CrossTrainingGoal),
  'themePreference' : IDL.Text,
  'trainingMilestones' : IDL.Vec(TrainingMilestone),
  'practitionerSince' : IDL.Opt(Time),
  'profilePicture' : IDL.Opt(ExternalBlob),
  'trainingGoals' : IDL.Vec(TrainingGoal),
});
export const SubmissionCount = IDL.Record({
  'name' : IDL.Text,
  'count' : IDL.Nat,
});
export const SubmissionLog = IDL.Record({
  'blackBelt' : IDL.Vec(SubmissionCount),
  'brownBelt' : IDL.Vec(SubmissionCount),
  'blueBelt' : IDL.Vec(SubmissionCount),
  'purpleBelt' : IDL.Vec(SubmissionCount),
});
export const SystemStatus = IDL.Record({
  'status' : IDL.Text,
  'userProfilesCount' : IDL.Nat,
  'customTypesCount' : IDL.Nat,
  'trainingHoursCount' : IDL.Nat,
  'trainingSessionsCount' : IDL.Nat,
  'techniquesCount' : IDL.Nat,
});
export const Belt = IDL.Variant({
  'blue' : IDL.Null,
  'purple' : IDL.Null,
  'black' : IDL.Null,
  'brown' : IDL.Null,
});
export const ExtendedProfile = IDL.Record({
  'bio' : IDL.Text,
  'gym' : IDL.Opt(GymInfo),
  'beltProgress' : BeltProgress,
  'nickname' : IDL.Text,
  'username' : IDL.Text,
  'streakAchievements' : IDL.Vec(StreakAchievement),
  'crossTrainingGoals' : IDL.Vec(CrossTrainingGoal),
  'trainingMilestones' : IDL.Vec(TrainingMilestone),
  'practitionerSince' : IDL.Opt(Time),
  'profilePicture' : IDL.Opt(ExternalBlob),
  'trainingGoals' : IDL.Vec(TrainingGoal),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCustomTechniqueType' : IDL.Func([IDL.Text], [], []),
  'addTechnique' : IDL.Func([Technique], [], []),
  'addTrainingHours' : IDL.Func([IDL.Text, IDL.Float64], [], []),
  'addTrainingRecord' : IDL.Func([TrainingSession], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'batchSetTrainingHours' : IDL.Func([IDL.Vec(TrainingHourRecord)], [], []),
  'batchUpdateTrainingHours' : IDL.Func([IDL.Vec(TrainingHourRecord)], [], []),
  'checkProfileStatus' : IDL.Func(
      [],
      [IDL.Record({ 'isDone' : IDL.Bool, 'profile' : IDL.Opt(UserProfile) })],
      ['query'],
    ),
  'clearAllTrainingHours' : IDL.Func([], [], []),
  'clearTrainingHours' : IDL.Func([IDL.Text], [], []),
  'deleteTrainingHours' : IDL.Func([IDL.Text], [], []),
  'getAllBeltProgress' : IDL.Func([], [IDL.Vec(BeltProgress)], ['query']),
  'getAllTechniques' : IDL.Func([], [IDL.Vec(Technique)], ['query']),
  'getAllTrainingHours' : IDL.Func(
      [],
      [IDL.Vec(TrainingHourRecord)],
      ['query'],
    ),
  'getAllUsersTrainingHours' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(TrainingHourRecord)))],
      ['query'],
    ),
  'getBeltProgress' : IDL.Func([], [IDL.Opt(BeltProgress)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCustomTechniqueTypes' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getDashboardData' : IDL.Func([], [IDL.Text], ['query']),
  'getSubmissionCountsByBelt' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(SubmissionCount)],
      ['query'],
    ),
  'getSubmissionLog' : IDL.Func([], [SubmissionLog], ['query']),
  'getSystemStatus' : IDL.Func([], [SystemStatus], ['query']),
  'getTechniques' : IDL.Func([], [IDL.Vec(Technique)], ['query']),
  'getThemePreference' : IDL.Func([], [IDL.Text], ['query']),
  'getTrainingHours' : IDL.Func([IDL.Text], [IDL.Float64], ['query']),
  'getTrainingHoursCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getTrainingHoursForAllUsers' : IDL.Func(
      [],
      [IDL.Vec(TrainingHourRecord)],
      ['query'],
    ),
  'getTrainingHoursRange' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(TrainingHourRecord)],
      ['query'],
    ),
  'getTrainingRecords' : IDL.Func([], [IDL.Vec(TrainingSession)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserProfilesCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserThemePreference' : IDL.Func([IDL.Principal], [IDL.Text], ['query']),
  'getUserTrainingHoursCount' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
  'hasBeltSubmission' : IDL.Func([Belt, IDL.Text], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isProfileCreationCompleted' : IDL.Func([], [IDL.Bool], ['query']),
  'markProfileCreationComplete' : IDL.Func([], [], []),
  'markProfileCreationStarted' : IDL.Func([], [], []),
  'register' : IDL.Func(
      [
        IDL.Text,
        BeltProgress,
        IDL.Opt(ExternalBlob),
        IDL.Opt(GymInfo),
        IDL.Opt(Time),
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveExtendedProfile' : IDL.Func([ExtendedProfile], [], []),
  'saveSubmissionLog' : IDL.Func([SubmissionLog], [], []),
  'saveTrainingRecords' : IDL.Func([IDL.Vec(TrainingSession)], [], []),
  'setTrainingHours' : IDL.Func([IDL.Text, IDL.Float64], [], []),
  'startProfileCreation' : IDL.Func(
      [],
      [IDL.Record({ 'isDone' : IDL.Bool, 'profile' : IDL.Opt(UserProfile) })],
      ['query'],
    ),
  'updateBeltProgress' : IDL.Func([BeltProgress], [], []),
  'updateDashboardData' : IDL.Func([IDL.Text], [], []),
  'updateThemePreference' : IDL.Func([IDL.Text], [], []),
  'updateTrainingHours' : IDL.Func([IDL.Text, IDL.Float64], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const SessionTheme = IDL.Variant({
    'openMat' : IDL.Null,
    'takedowns_standup' : IDL.Null,
    'turtleGame' : IDL.Null,
    'transitionsScrambles' : IDL.Null,
    'submissions' : IDL.Null,
    'pinsControl' : IDL.Null,
    'backControl' : IDL.Null,
    'guardRetention' : IDL.Null,
    'escapes' : IDL.Null,
    'sweeps' : IDL.Null,
    'legLocks' : IDL.Null,
    'guardPassing' : IDL.Null,
    'guardSystems' : IDL.Null,
  });
  const Technique = IDL.Record({
    'id' : IDL.Text,
    'typ' : IDL.Text,
    'thumbnail' : IDL.Opt(ExternalBlob),
    'link' : IDL.Text,
    'name' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'linkedSessions' : IDL.Vec(IDL.Text),
    'category' : SessionTheme,
  });
  const Time = IDL.Int;
  const TrainingType = IDL.Variant({ 'gi' : IDL.Null, 'noGi' : IDL.Null });
  const TrainingSession = IDL.Record({
    'id' : IDL.Text,
    'duration' : IDL.Nat,
    'date' : Time,
    'moodRating' : IDL.Float64,
    'sessionTheme' : SessionTheme,
    'trainingType' : TrainingType,
    'rolls' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const TrainingHourRecord = IDL.Record({
    'hours' : IDL.Float64,
    'date' : IDL.Text,
  });
  const GymInfo = IDL.Record({
    'name' : IDL.Text,
    'logoUrl' : IDL.Opt(IDL.Text),
    'location' : IDL.Text,
  });
  const BeltLevel = IDL.Variant({
    'blue' : IDL.Null,
    'purple' : IDL.Null,
    'black' : IDL.Null,
    'brown' : IDL.Null,
    'white' : IDL.Null,
  });
  const BeltProgress = IDL.Record({
    'belt' : BeltLevel,
    'imageUrl' : IDL.Text,
    'stripes' : IDL.Nat,
  });
  const StreakAchievement = IDL.Record({
    'id' : IDL.Text,
    'endDate' : Time,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'streakLength' : IDL.Nat,
    'startDate' : Time,
  });
  const CrossTrainingGoal = IDL.Record({
    'id' : IDL.Text,
    'completionDate' : IDL.Opt(Time),
    'name' : IDL.Text,
    'description' : IDL.Text,
    'progress' : IDL.Nat,
    'targetArea' : IDL.Text,
  });
  const TrainingMilestone = IDL.Record({
    'id' : IDL.Text,
    'beltProgress' : IDL.Opt(BeltProgress),
    'achievedDate' : Time,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const TrainingGoal = IDL.Record({
    'id' : IDL.Text,
    'completedRepetitions' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'deadline' : IDL.Opt(Time),
    'creationDate' : Time,
    'targetRepetitions' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'gym' : IDL.Opt(GymInfo),
    'beltProgress' : BeltProgress,
    'nickname' : IDL.Text,
    'username' : IDL.Text,
    'streakAchievements' : IDL.Vec(StreakAchievement),
    'crossTrainingGoals' : IDL.Vec(CrossTrainingGoal),
    'themePreference' : IDL.Text,
    'trainingMilestones' : IDL.Vec(TrainingMilestone),
    'practitionerSince' : IDL.Opt(Time),
    'profilePicture' : IDL.Opt(ExternalBlob),
    'trainingGoals' : IDL.Vec(TrainingGoal),
  });
  const SubmissionCount = IDL.Record({ 'name' : IDL.Text, 'count' : IDL.Nat });
  const SubmissionLog = IDL.Record({
    'blackBelt' : IDL.Vec(SubmissionCount),
    'brownBelt' : IDL.Vec(SubmissionCount),
    'blueBelt' : IDL.Vec(SubmissionCount),
    'purpleBelt' : IDL.Vec(SubmissionCount),
  });
  const SystemStatus = IDL.Record({
    'status' : IDL.Text,
    'userProfilesCount' : IDL.Nat,
    'customTypesCount' : IDL.Nat,
    'trainingHoursCount' : IDL.Nat,
    'trainingSessionsCount' : IDL.Nat,
    'techniquesCount' : IDL.Nat,
  });
  const Belt = IDL.Variant({
    'blue' : IDL.Null,
    'purple' : IDL.Null,
    'black' : IDL.Null,
    'brown' : IDL.Null,
  });
  const ExtendedProfile = IDL.Record({
    'bio' : IDL.Text,
    'gym' : IDL.Opt(GymInfo),
    'beltProgress' : BeltProgress,
    'nickname' : IDL.Text,
    'username' : IDL.Text,
    'streakAchievements' : IDL.Vec(StreakAchievement),
    'crossTrainingGoals' : IDL.Vec(CrossTrainingGoal),
    'trainingMilestones' : IDL.Vec(TrainingMilestone),
    'practitionerSince' : IDL.Opt(Time),
    'profilePicture' : IDL.Opt(ExternalBlob),
    'trainingGoals' : IDL.Vec(TrainingGoal),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCustomTechniqueType' : IDL.Func([IDL.Text], [], []),
    'addTechnique' : IDL.Func([Technique], [], []),
    'addTrainingHours' : IDL.Func([IDL.Text, IDL.Float64], [], []),
    'addTrainingRecord' : IDL.Func([TrainingSession], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'batchSetTrainingHours' : IDL.Func([IDL.Vec(TrainingHourRecord)], [], []),
    'batchUpdateTrainingHours' : IDL.Func(
        [IDL.Vec(TrainingHourRecord)],
        [],
        [],
      ),
    'checkProfileStatus' : IDL.Func(
        [],
        [IDL.Record({ 'isDone' : IDL.Bool, 'profile' : IDL.Opt(UserProfile) })],
        ['query'],
      ),
    'clearAllTrainingHours' : IDL.Func([], [], []),
    'clearTrainingHours' : IDL.Func([IDL.Text], [], []),
    'deleteTrainingHours' : IDL.Func([IDL.Text], [], []),
    'getAllBeltProgress' : IDL.Func([], [IDL.Vec(BeltProgress)], ['query']),
    'getAllTechniques' : IDL.Func([], [IDL.Vec(Technique)], ['query']),
    'getAllTrainingHours' : IDL.Func(
        [],
        [IDL.Vec(TrainingHourRecord)],
        ['query'],
      ),
    'getAllUsersTrainingHours' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(TrainingHourRecord)))],
        ['query'],
      ),
    'getBeltProgress' : IDL.Func([], [IDL.Opt(BeltProgress)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCustomTechniqueTypes' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getDashboardData' : IDL.Func([], [IDL.Text], ['query']),
    'getSubmissionCountsByBelt' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(SubmissionCount)],
        ['query'],
      ),
    'getSubmissionLog' : IDL.Func([], [SubmissionLog], ['query']),
    'getSystemStatus' : IDL.Func([], [SystemStatus], ['query']),
    'getTechniques' : IDL.Func([], [IDL.Vec(Technique)], ['query']),
    'getThemePreference' : IDL.Func([], [IDL.Text], ['query']),
    'getTrainingHours' : IDL.Func([IDL.Text], [IDL.Float64], ['query']),
    'getTrainingHoursCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getTrainingHoursForAllUsers' : IDL.Func(
        [],
        [IDL.Vec(TrainingHourRecord)],
        ['query'],
      ),
    'getTrainingHoursRange' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(TrainingHourRecord)],
        ['query'],
      ),
    'getTrainingRecords' : IDL.Func([], [IDL.Vec(TrainingSession)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserProfilesCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserThemePreference' : IDL.Func([IDL.Principal], [IDL.Text], ['query']),
    'getUserTrainingHoursCount' : IDL.Func(
        [IDL.Principal],
        [IDL.Nat],
        ['query'],
      ),
    'hasBeltSubmission' : IDL.Func([Belt, IDL.Text], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isProfileCreationCompleted' : IDL.Func([], [IDL.Bool], ['query']),
    'markProfileCreationComplete' : IDL.Func([], [], []),
    'markProfileCreationStarted' : IDL.Func([], [], []),
    'register' : IDL.Func(
        [
          IDL.Text,
          BeltProgress,
          IDL.Opt(ExternalBlob),
          IDL.Opt(GymInfo),
          IDL.Opt(Time),
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveExtendedProfile' : IDL.Func([ExtendedProfile], [], []),
    'saveSubmissionLog' : IDL.Func([SubmissionLog], [], []),
    'saveTrainingRecords' : IDL.Func([IDL.Vec(TrainingSession)], [], []),
    'setTrainingHours' : IDL.Func([IDL.Text, IDL.Float64], [], []),
    'startProfileCreation' : IDL.Func(
        [],
        [IDL.Record({ 'isDone' : IDL.Bool, 'profile' : IDL.Opt(UserProfile) })],
        ['query'],
      ),
    'updateBeltProgress' : IDL.Func([BeltProgress], [], []),
    'updateDashboardData' : IDL.Func([IDL.Text], [], []),
    'updateThemePreference' : IDL.Func([IDL.Text], [], []),
    'updateTrainingHours' : IDL.Func([IDL.Text, IDL.Float64], [], []),
  });
};

export const init = ({ IDL }) => { return []; };