/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Belt = { 'blue' : null } |
  { 'purple' : null } |
  { 'black' : null } |
  { 'brown' : null } |
  { 'white' : null };
export type BeltLevel = { 'blue' : null } |
  { 'purple' : null } |
  { 'black' : null } |
  { 'brown' : null } |
  { 'white' : null };
export interface BeltProgress {
  'belt' : BeltLevel,
  'imageUrl' : string,
  'stripes' : bigint,
}
export interface CrossTrainingGoal {
  'id' : string,
  'completionDate' : [] | [Time],
  'name' : string,
  'description' : string,
  'progress' : bigint,
  'targetArea' : string,
}
export interface ExtendedProfile {
  'bio' : string,
  'gym' : [] | [GymInfo],
  'beltProgress' : BeltProgress,
  'nickname' : string,
  'username' : string,
  'streakAchievements' : Array<StreakAchievement>,
  'crossTrainingGoals' : Array<CrossTrainingGoal>,
  'trainingMilestones' : Array<TrainingMilestone>,
  'practitionerSince' : [] | [Time],
  'profilePicture' : [] | [ExternalBlob],
  'trainingGoals' : Array<TrainingGoal>,
}
export type ExternalBlob = Uint8Array;
export interface GymInfo {
  'name' : string,
  'logoUrl' : [] | [string],
  'location' : string,
}
export type Intensity = { 'recoveryFlow' : null } |
  { 'hard' : null } |
  { 'light' : null } |
  { 'maxComp' : null } |
  { 'moderate' : null };
export type SessionTheme = { 'openMat' : null } |
  { 'takedowns_standup' : null } |
  { 'turtleGame' : null } |
  { 'transitionsScrambles' : null } |
  { 'submissions' : null } |
  { 'pinsControl' : null } |
  { 'backControl' : null } |
  { 'guardRetention' : null } |
  { 'escapes' : null } |
  { 'sweeps' : null } |
  { 'legLocks' : null } |
  { 'guardPassing' : null } |
  { 'guardSystems' : null };
export interface StreakAchievement {
  'id' : string,
  'endDate' : Time,
  'name' : string,
  'description' : string,
  'streakLength' : bigint,
  'startDate' : Time,
}
export interface SubmissionCount { 'name' : string, 'count' : bigint }
export interface SubmissionLog {
  'blackBelt' : Array<SubmissionCount>,
  'whiteBelt' : Array<SubmissionCount>,
  'brownBelt' : Array<SubmissionCount>,
  'blueBelt' : Array<SubmissionCount>,
  'purpleBelt' : Array<SubmissionCount>,
}
export interface SystemStatus {
  'status' : string,
  'userProfilesCount' : bigint,
  'customTypesCount' : bigint,
  'trainingHoursCount' : bigint,
  'trainingSessionsCount' : bigint,
  'techniquesCount' : bigint,
}
export interface Technique {
  'id' : string,
  'typ' : string,
  'thumbnail' : [] | [ExternalBlob],
  'link' : string,
  'name' : string,
  'tags' : Array<string>,
  'description' : string,
  'linkedSessions' : Array<string>,
  'category' : SessionTheme,
}
export type Time = bigint;
export interface TrainingGoal {
  'id' : string,
  'completedRepetitions' : bigint,
  'name' : string,
  'description' : string,
  'deadline' : [] | [Time],
  'creationDate' : Time,
  'targetRepetitions' : bigint,
}
export interface TrainingHourRecord { 'hours' : number, 'date' : string }
export interface TrainingMilestone {
  'id' : string,
  'beltProgress' : [] | [BeltProgress],
  'achievedDate' : Time,
  'name' : string,
  'description' : string,
}
export interface TrainingSession {
  'id' : string,
  'duration' : bigint,
  'date' : Time,
  'moodRating' : number,
  'sessionTheme' : SessionTheme,
  'trainingType' : TrainingType,
  'beltSnapshot' : BeltProgress,
  'rolls' : bigint,
  'intensity' : Intensity,
}
export type TrainingType = { 'gi' : null } |
  { 'noGi' : null };
export interface UserProfile {
  'bio' : string,
  'gym' : [] | [GymInfo],
  'beltProgress' : BeltProgress,
  'nickname' : string,
  'username' : string,
  'streakAchievements' : Array<StreakAchievement>,
  'crossTrainingGoals' : Array<CrossTrainingGoal>,
  'themePreference' : string,
  'trainingMilestones' : Array<TrainingMilestone>,
  'practitionerSince' : [] | [Time],
  'profilePicture' : [] | [ExternalBlob],
  'trainingGoals' : Array<TrainingGoal>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCustomTechniqueType' : ActorMethod<[string], undefined>,
  'addTechnique' : ActorMethod<[Technique], undefined>,
  'addTrainingHours' : ActorMethod<[string, number], undefined>,
  'addTrainingRecord' : ActorMethod<[TrainingSession], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'batchSetTrainingHours' : ActorMethod<[Array<TrainingHourRecord>], undefined>,
  'batchUpdateTrainingHours' : ActorMethod<
    [Array<TrainingHourRecord>],
    undefined
  >,
  'checkProfileStatus' : ActorMethod<
    [],
    { 'isDone' : boolean, 'profile' : [] | [UserProfile] }
  >,
  'clearAllTrainingHours' : ActorMethod<[], undefined>,
  'clearTrainingHours' : ActorMethod<[string], undefined>,
  'deleteTrainingHours' : ActorMethod<[string], undefined>,
  'getAllBeltProgress' : ActorMethod<[], Array<BeltProgress>>,
  'getAllTechniques' : ActorMethod<[], Array<Technique>>,
  'getAllTrainingHours' : ActorMethod<[], Array<TrainingHourRecord>>,
  'getAllUsersTrainingHours' : ActorMethod<
    [],
    Array<[Principal, Array<TrainingHourRecord>]>
  >,
  'getBeltProgress' : ActorMethod<[], [] | [BeltProgress]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCustomTechniqueTypes' : ActorMethod<[], Array<string>>,
  'getDashboardData' : ActorMethod<[], string>,
  'getSubmissionCountsByBelt' : ActorMethod<[string], Array<SubmissionCount>>,
  'getSubmissionLog' : ActorMethod<[], SubmissionLog>,
  'getSystemStatus' : ActorMethod<[], SystemStatus>,
  'getTechniques' : ActorMethod<[], Array<Technique>>,
  'getThemePreference' : ActorMethod<[], string>,
  'getTrainingHours' : ActorMethod<[string], number>,
  'getTrainingHoursCount' : ActorMethod<[], bigint>,
  'getTrainingHoursForAllUsers' : ActorMethod<[], Array<TrainingHourRecord>>,
  'getTrainingHoursRange' : ActorMethod<
    [string, string],
    Array<TrainingHourRecord>
  >,
  'getTrainingRecords' : ActorMethod<[], Array<TrainingSession>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserProfilesCount' : ActorMethod<[], bigint>,
  'getUserThemePreference' : ActorMethod<[Principal], string>,
  'getUserTrainingHoursCount' : ActorMethod<[Principal], bigint>,
  'hasBeltSubmission' : ActorMethod<[Belt, string], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isProfileCreationCompleted' : ActorMethod<[], boolean>,
  'markProfileCreationComplete' : ActorMethod<[], undefined>,
  'markProfileCreationStarted' : ActorMethod<[], undefined>,
  'register' : ActorMethod<
    [
      string,
      BeltProgress,
      [] | [ExternalBlob],
      [] | [GymInfo],
      [] | [Time],
      string,
      string,
    ],
    undefined
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveExtendedProfile' : ActorMethod<[ExtendedProfile], undefined>,
  'saveSubmissionLog' : ActorMethod<[SubmissionLog], undefined>,
  'saveTrainingRecords' : ActorMethod<[Array<TrainingSession>], undefined>,
  'setTrainingHours' : ActorMethod<[string, number], undefined>,
  'startProfileCreation' : ActorMethod<
    [],
    { 'isDone' : boolean, 'profile' : [] | [UserProfile] }
  >,
  'updateBeltProgress' : ActorMethod<[BeltProgress], undefined>,
  'updateDashboardData' : ActorMethod<[string], undefined>,
  'updateThemePreference' : ActorMethod<[string], undefined>,
  'updateTrainingHours' : ActorMethod<[string, number], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];