/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface GymInfo {
    name: string;
    logoUrl?: string;
    location: string;
}
export type Time = bigint;
export interface BeltProgress {
    belt: BeltLevel;
    imageUrl: string;
    stripes: bigint;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface CrossTrainingGoal {
    id: string;
    completionDate?: Time;
    name: string;
    description: string;
    progress: bigint;
    targetArea: string;
}
export interface Technique {
    id: string;
    typ: string;
    thumbnail?: ExternalBlob;
    link: string;
    name: string;
    tags: Array<string>;
    description: string;
    linkedSessions: Array<string>;
    category: SessionTheme;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface TrainingHourRecord {
    hours: number;
    date: string;
}
export interface ExtendedProfile {
    bio: string;
    gym?: GymInfo;
    beltProgress: BeltProgress;
    nickname: string;
    username: string;
    streakAchievements: Array<StreakAchievement>;
    crossTrainingGoals: Array<CrossTrainingGoal>;
    trainingMilestones: Array<TrainingMilestone>;
    practitionerSince?: Time;
    profilePicture?: ExternalBlob;
    trainingGoals: Array<TrainingGoal>;
}
export interface SubmissionLog {
    blackBelt: Array<SubmissionCount>;
    brownBelt: Array<SubmissionCount>;
    blueBelt: Array<SubmissionCount>;
    purpleBelt: Array<SubmissionCount>;
}
export interface TrainingSession {
    id: string;
    duration: bigint;
    date: Time;
    moodRating: number;
    sessionTheme: SessionTheme;
    trainingType: TrainingType;
    rolls: bigint;
}
export interface TrainingMilestone {
    id: string;
    beltProgress?: BeltProgress;
    achievedDate: Time;
    name: string;
    description: string;
}
export interface StreakAchievement {
    id: string;
    endDate: Time;
    name: string;
    description: string;
    streakLength: bigint;
    startDate: Time;
}
export interface TrainingGoal {
    id: string;
    completedRepetitions: bigint;
    name: string;
    description: string;
    deadline?: Time;
    creationDate: Time;
    targetRepetitions: bigint;
}
export interface SubmissionCount {
    name: string;
    count: bigint;
}
export interface UserProfile {
    bio: string;
    gym?: GymInfo;
    beltProgress: BeltProgress;
    nickname: string;
    username: string;
    streakAchievements: Array<StreakAchievement>;
    crossTrainingGoals: Array<CrossTrainingGoal>;
    themePreference: string;
    trainingMilestones: Array<TrainingMilestone>;
    practitionerSince?: Time;
    profilePicture?: ExternalBlob;
    trainingGoals: Array<TrainingGoal>;
}
export interface SystemStatus {
    status: string;
    userProfilesCount: bigint;
    customTypesCount: bigint;
    trainingHoursCount: bigint;
    trainingSessionsCount: bigint;
    techniquesCount: bigint;
}
export enum Belt {
    blue = "blue",
    purple = "purple",
    black = "black",
    brown = "brown"
}
export enum BeltLevel {
    blue = "blue",
    purple = "purple",
    black = "black",
    brown = "brown",
    white = "white"
}
export enum SessionTheme {
    openMat = "openMat",
    takedowns_standup = "takedowns_standup",
    turtleGame = "turtleGame",
    transitionsScrambles = "transitionsScrambles",
    submissions = "submissions",
    pinsControl = "pinsControl",
    backControl = "backControl",
    guardRetention = "guardRetention",
    escapes = "escapes",
    sweeps = "sweeps",
    legLocks = "legLocks",
    guardPassing = "guardPassing",
    guardSystems = "guardSystems"
}
export enum TrainingType {
    gi = "gi",
    noGi = "noGi"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addCustomTechniqueType(typeName: string): Promise<void>;
    addTechnique(newTechnique: Technique): Promise<void>;
    addTrainingHours(date: string, hours: number): Promise<void>;
    addTrainingRecord(training: TrainingSession): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    batchSetTrainingHours(records: Array<TrainingHourRecord>): Promise<void>;
    batchUpdateTrainingHours(records: Array<TrainingHourRecord>): Promise<void>;
    checkProfileStatus(): Promise<{
        isDone: boolean;
        profile?: UserProfile;
    }>;
    clearAllTrainingHours(): Promise<void>;
    clearTrainingHours(date: string): Promise<void>;
    deleteTrainingHours(date: string): Promise<void>;
    getAllBeltProgress(): Promise<Array<BeltProgress>>;
    getAllTechniques(): Promise<Array<Technique>>;
    getAllTrainingHours(): Promise<Array<TrainingHourRecord>>;
    getAllUsersTrainingHours(): Promise<Array<[Principal, Array<TrainingHourRecord>]>>;
    getBeltProgress(): Promise<BeltProgress | null>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCustomTechniqueTypes(): Promise<Array<string>>;
    getDashboardData(): Promise<string>;
    getSubmissionCountsByBelt(belt: string): Promise<Array<SubmissionCount>>;
    getSubmissionLog(): Promise<SubmissionLog>;
    getSystemStatus(): Promise<SystemStatus>;
    getTechniques(): Promise<Array<Technique>>;
    getThemePreference(): Promise<string>;
    getTrainingHours(date: string): Promise<number>;
    getTrainingHoursCount(): Promise<bigint>;
    getTrainingHoursForAllUsers(): Promise<Array<TrainingHourRecord>>;
    getTrainingHoursRange(startDate: string, endDate: string): Promise<Array<TrainingHourRecord>>;
    getTrainingRecords(): Promise<Array<TrainingSession>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getUserProfilesCount(): Promise<bigint>;
    getUserThemePreference(user: Principal): Promise<string>;
    getUserTrainingHoursCount(user: Principal): Promise<bigint>;
    hasBeltSubmission(belt: Belt, submissionName: string): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    isProfileCreationCompleted(): Promise<boolean>;
    markProfileCreationComplete(): Promise<void>;
    markProfileCreationStarted(): Promise<void>;
    register(username: string, beltProgress: BeltProgress, profilePicture: ExternalBlob | null, gym: GymInfo | null, practitionerSince: Time | null, bio: string, nickname: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveExtendedProfile(profile: ExtendedProfile): Promise<void>;
    saveSubmissionLog(newLog: SubmissionLog): Promise<void>;
    saveTrainingRecords(trainingRecords: Array<TrainingSession>): Promise<void>;
    setTrainingHours(date: string, hours: number): Promise<void>;
    startProfileCreation(): Promise<{
        isDone: boolean;
        profile?: UserProfile;
    }>;
    updateBeltProgress(beltProgress: BeltProgress): Promise<void>;
    updateDashboardData(dashboardData: string): Promise<void>;
    updateThemePreference(theme: string): Promise<void>;
    updateTrainingHours(date: string, hours: number): Promise<void>;
}
import type { Belt as _Belt, BeltLevel as _BeltLevel, BeltProgress as _BeltProgress, CrossTrainingGoal as _CrossTrainingGoal, ExtendedProfile as _ExtendedProfile, ExternalBlob as _ExternalBlob, GymInfo as _GymInfo, SessionTheme as _SessionTheme, StreakAchievement as _StreakAchievement, Technique as _Technique, Time as _Time, TrainingGoal as _TrainingGoal, TrainingMilestone as _TrainingMilestone, TrainingSession as _TrainingSession, TrainingType as _TrainingType, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addCustomTechniqueType(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addCustomTechniqueType(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCustomTechniqueType(arg0);
            return result;
        }
    }
    async addTechnique(arg0: Technique): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addTechnique(await to_candid_Technique_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTechnique(await to_candid_Technique_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addTrainingHours(arg0: string, arg1: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addTrainingHours(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTrainingHours(arg0, arg1);
            return result;
        }
    }
    async addTrainingRecord(arg0: TrainingSession): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addTrainingRecord(to_candid_TrainingSession_n13(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTrainingRecord(to_candid_TrainingSession_n13(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n17(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n17(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async batchSetTrainingHours(arg0: Array<TrainingHourRecord>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.batchSetTrainingHours(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.batchSetTrainingHours(arg0);
            return result;
        }
    }
    async batchUpdateTrainingHours(arg0: Array<TrainingHourRecord>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.batchUpdateTrainingHours(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.batchUpdateTrainingHours(arg0);
            return result;
        }
    }
    async checkProfileStatus(): Promise<{
        isDone: boolean;
        profile?: UserProfile;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.checkProfileStatus();
                return from_candid_record_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkProfileStatus();
            return from_candid_record_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async clearAllTrainingHours(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearAllTrainingHours();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearAllTrainingHours();
            return result;
        }
    }
    async clearTrainingHours(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearTrainingHours(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearTrainingHours(arg0);
            return result;
        }
    }
    async deleteTrainingHours(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTrainingHours(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTrainingHours(arg0);
            return result;
        }
    }
    async getAllBeltProgress(): Promise<Array<BeltProgress>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBeltProgress();
                return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBeltProgress();
            return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllTechniques(): Promise<Array<Technique>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTechniques();
                return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTechniques();
            return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllTrainingHours(): Promise<Array<TrainingHourRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTrainingHours();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTrainingHours();
            return result;
        }
    }
    async getAllUsersTrainingHours(): Promise<Array<[Principal, Array<TrainingHourRecord>]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUsersTrainingHours();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUsersTrainingHours();
            return result;
        }
    }
    async getBeltProgress(): Promise<BeltProgress | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBeltProgress();
                return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBeltProgress();
            return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCustomTechniqueTypes(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomTechniqueTypes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomTechniqueTypes();
            return result;
        }
    }
    async getDashboardData(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardData();
            return result;
        }
    }
    async getSubmissionCountsByBelt(arg0: string): Promise<Array<SubmissionCount>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSubmissionCountsByBelt(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSubmissionCountsByBelt(arg0);
            return result;
        }
    }
    async getSubmissionLog(): Promise<SubmissionLog> {
        if (this.processError) {
            try {
                const result = await this.actor.getSubmissionLog();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSubmissionLog();
            return result;
        }
    }
    async getSystemStatus(): Promise<SystemStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getSystemStatus();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSystemStatus();
            return result;
        }
    }
    async getTechniques(): Promise<Array<Technique>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTechniques();
                return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTechniques();
            return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getThemePreference(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getThemePreference();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getThemePreference();
            return result;
        }
    }
    async getTrainingHours(arg0: string): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getTrainingHours(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTrainingHours(arg0);
            return result;
        }
    }
    async getTrainingHoursCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTrainingHoursCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTrainingHoursCount();
            return result;
        }
    }
    async getTrainingHoursForAllUsers(): Promise<Array<TrainingHourRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTrainingHoursForAllUsers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTrainingHoursForAllUsers();
            return result;
        }
    }
    async getTrainingHoursRange(arg0: string, arg1: string): Promise<Array<TrainingHourRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTrainingHoursRange(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTrainingHoursRange(arg0, arg1);
            return result;
        }
    }
    async getTrainingRecords(): Promise<Array<TrainingSession>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTrainingRecords();
                return from_candid_vec_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTrainingRecords();
            return from_candid_vec_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfilesCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfilesCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfilesCount();
            return result;
        }
    }
    async getUserThemePreference(arg0: Principal): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserThemePreference(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserThemePreference(arg0);
            return result;
        }
    }
    async getUserTrainingHoursCount(arg0: Principal): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserTrainingHoursCount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserTrainingHoursCount(arg0);
            return result;
        }
    }
    async hasBeltSubmission(arg0: Belt, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.hasBeltSubmission(to_candid_Belt_n57(this._uploadFile, this._downloadFile, arg0), arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hasBeltSubmission(to_candid_Belt_n57(this._uploadFile, this._downloadFile, arg0), arg1);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isProfileCreationCompleted(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isProfileCreationCompleted();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isProfileCreationCompleted();
            return result;
        }
    }
    async markProfileCreationComplete(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markProfileCreationComplete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markProfileCreationComplete();
            return result;
        }
    }
    async markProfileCreationStarted(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markProfileCreationStarted();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markProfileCreationStarted();
            return result;
        }
    }
    async register(arg0: string, arg1: BeltProgress, arg2: ExternalBlob | null, arg3: GymInfo | null, arg4: Time | null, arg5: string, arg6: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.register(arg0, to_candid_BeltProgress_n59(this._uploadFile, this._downloadFile, arg1), await to_candid_opt_n63(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n64(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n67(this._uploadFile, this._downloadFile, arg4), arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.register(arg0, to_candid_BeltProgress_n59(this._uploadFile, this._downloadFile, arg1), await to_candid_opt_n63(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n64(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n67(this._uploadFile, this._downloadFile, arg4), arg5, arg6);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(await to_candid_UserProfile_n68(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(await to_candid_UserProfile_n68(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveExtendedProfile(arg0: ExtendedProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveExtendedProfile(await to_candid_ExtendedProfile_n79(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveExtendedProfile(await to_candid_ExtendedProfile_n79(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveSubmissionLog(arg0: SubmissionLog): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveSubmissionLog(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveSubmissionLog(arg0);
            return result;
        }
    }
    async saveTrainingRecords(arg0: Array<TrainingSession>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveTrainingRecords(to_candid_vec_n81(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveTrainingRecords(to_candid_vec_n81(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setTrainingHours(arg0: string, arg1: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setTrainingHours(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setTrainingHours(arg0, arg1);
            return result;
        }
    }
    async startProfileCreation(): Promise<{
        isDone: boolean;
        profile?: UserProfile;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.startProfileCreation();
                return from_candid_record_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.startProfileCreation();
            return from_candid_record_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateBeltProgress(arg0: BeltProgress): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBeltProgress(to_candid_BeltProgress_n59(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBeltProgress(to_candid_BeltProgress_n59(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateDashboardData(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDashboardData(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDashboardData(arg0);
            return result;
        }
    }
    async updateThemePreference(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateThemePreference(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateThemePreference(arg0);
            return result;
        }
    }
    async updateTrainingHours(arg0: string, arg1: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTrainingHours(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTrainingHours(arg0, arg1);
            return result;
        }
    }
}
function from_candid_BeltLevel_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BeltLevel): BeltLevel {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function from_candid_BeltProgress_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BeltProgress): BeltProgress {
    return from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_CrossTrainingGoal_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CrossTrainingGoal): CrossTrainingGoal {
    return from_candid_record_n33(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_GymInfo_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GymInfo): GymInfo {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_SessionTheme_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SessionTheme): SessionTheme {
    return from_candid_variant_n49(_uploadFile, _downloadFile, value);
}
async function from_candid_Technique_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Technique): Promise<Technique> {
    return await from_candid_record_n47(_uploadFile, _downloadFile, value);
}
function from_candid_TrainingGoal_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TrainingGoal): TrainingGoal {
    return from_candid_record_n43(_uploadFile, _downloadFile, value);
}
function from_candid_TrainingMilestone_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TrainingMilestone): TrainingMilestone {
    return from_candid_record_n37(_uploadFile, _downloadFile, value);
}
function from_candid_TrainingSession_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TrainingSession): TrainingSession {
    return from_candid_record_n54(_uploadFile, _downloadFile, value);
}
function from_candid_TrainingType_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TrainingType): TrainingType {
    return from_candid_variant_n56(_uploadFile, _downloadFile, value);
}
async function from_candid_UserProfile_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): Promise<UserProfile> {
    return await from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n51(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): Promise<UserProfile | null> {
    return value.length === 0 ? null : await from_candid_UserProfile_n21(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_GymInfo]): GymInfo | null {
    return value.length === 0 ? null : from_candid_GymInfo_n24(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BeltProgress]): BeltProgress | null {
    return value.length === 0 ? null : from_candid_BeltProgress_n27(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n40(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    isDone: boolean;
    profile: [] | [_UserProfile];
}): Promise<{
    isDone: boolean;
    profile?: UserProfile;
}> {
    return {
        isDone: value.isDone,
        profile: record_opt_to_undefined(await from_candid_opt_n20(_uploadFile, _downloadFile, value.profile))
    };
}
async function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio: string;
    gym: [] | [_GymInfo];
    beltProgress: _BeltProgress;
    nickname: string;
    username: string;
    streakAchievements: Array<_StreakAchievement>;
    crossTrainingGoals: Array<_CrossTrainingGoal>;
    themePreference: string;
    trainingMilestones: Array<_TrainingMilestone>;
    practitionerSince: [] | [_Time];
    profilePicture: [] | [_ExternalBlob];
    trainingGoals: Array<_TrainingGoal>;
}): Promise<{
    bio: string;
    gym?: GymInfo;
    beltProgress: BeltProgress;
    nickname: string;
    username: string;
    streakAchievements: Array<StreakAchievement>;
    crossTrainingGoals: Array<CrossTrainingGoal>;
    themePreference: string;
    trainingMilestones: Array<TrainingMilestone>;
    practitionerSince?: Time;
    profilePicture?: ExternalBlob;
    trainingGoals: Array<TrainingGoal>;
}> {
    return {
        bio: value.bio,
        gym: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.gym)),
        beltProgress: from_candid_BeltProgress_n27(_uploadFile, _downloadFile, value.beltProgress),
        nickname: value.nickname,
        username: value.username,
        streakAchievements: value.streakAchievements,
        crossTrainingGoals: from_candid_vec_n31(_uploadFile, _downloadFile, value.crossTrainingGoals),
        themePreference: value.themePreference,
        trainingMilestones: from_candid_vec_n35(_uploadFile, _downloadFile, value.trainingMilestones),
        practitionerSince: record_opt_to_undefined(from_candid_opt_n34(_uploadFile, _downloadFile, value.practitionerSince)),
        profilePicture: record_opt_to_undefined(await from_candid_opt_n39(_uploadFile, _downloadFile, value.profilePicture)),
        trainingGoals: from_candid_vec_n41(_uploadFile, _downloadFile, value.trainingGoals)
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    logoUrl: [] | [string];
    location: string;
}): {
    name: string;
    logoUrl?: string;
    location: string;
} {
    return {
        name: value.name,
        logoUrl: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.logoUrl)),
        location: value.location
    };
}
function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    belt: _BeltLevel;
    imageUrl: string;
    stripes: bigint;
}): {
    belt: BeltLevel;
    imageUrl: string;
    stripes: bigint;
} {
    return {
        belt: from_candid_BeltLevel_n29(_uploadFile, _downloadFile, value.belt),
        imageUrl: value.imageUrl,
        stripes: value.stripes
    };
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    completionDate: [] | [_Time];
    name: string;
    description: string;
    progress: bigint;
    targetArea: string;
}): {
    id: string;
    completionDate?: Time;
    name: string;
    description: string;
    progress: bigint;
    targetArea: string;
} {
    return {
        id: value.id,
        completionDate: record_opt_to_undefined(from_candid_opt_n34(_uploadFile, _downloadFile, value.completionDate)),
        name: value.name,
        description: value.description,
        progress: value.progress,
        targetArea: value.targetArea
    };
}
function from_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    beltProgress: [] | [_BeltProgress];
    achievedDate: _Time;
    name: string;
    description: string;
}): {
    id: string;
    beltProgress?: BeltProgress;
    achievedDate: Time;
    name: string;
    description: string;
} {
    return {
        id: value.id,
        beltProgress: record_opt_to_undefined(from_candid_opt_n38(_uploadFile, _downloadFile, value.beltProgress)),
        achievedDate: value.achievedDate,
        name: value.name,
        description: value.description
    };
}
function from_candid_record_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    completedRepetitions: bigint;
    name: string;
    description: string;
    deadline: [] | [_Time];
    creationDate: _Time;
    targetRepetitions: bigint;
}): {
    id: string;
    completedRepetitions: bigint;
    name: string;
    description: string;
    deadline?: Time;
    creationDate: Time;
    targetRepetitions: bigint;
} {
    return {
        id: value.id,
        completedRepetitions: value.completedRepetitions,
        name: value.name,
        description: value.description,
        deadline: record_opt_to_undefined(from_candid_opt_n34(_uploadFile, _downloadFile, value.deadline)),
        creationDate: value.creationDate,
        targetRepetitions: value.targetRepetitions
    };
}
async function from_candid_record_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    typ: string;
    thumbnail: [] | [_ExternalBlob];
    link: string;
    name: string;
    tags: Array<string>;
    description: string;
    linkedSessions: Array<string>;
    category: _SessionTheme;
}): Promise<{
    id: string;
    typ: string;
    thumbnail?: ExternalBlob;
    link: string;
    name: string;
    tags: Array<string>;
    description: string;
    linkedSessions: Array<string>;
    category: SessionTheme;
}> {
    return {
        id: value.id,
        typ: value.typ,
        thumbnail: record_opt_to_undefined(await from_candid_opt_n39(_uploadFile, _downloadFile, value.thumbnail)),
        link: value.link,
        name: value.name,
        tags: value.tags,
        description: value.description,
        linkedSessions: value.linkedSessions,
        category: from_candid_SessionTheme_n48(_uploadFile, _downloadFile, value.category)
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    duration: bigint;
    date: _Time;
    moodRating: number;
    sessionTheme: _SessionTheme;
    trainingType: _TrainingType;
    rolls: bigint;
}): {
    id: string;
    duration: bigint;
    date: Time;
    moodRating: number;
    sessionTheme: SessionTheme;
    trainingType: TrainingType;
    rolls: bigint;
} {
    return {
        id: value.id,
        duration: value.duration,
        date: value.date,
        moodRating: value.moodRating,
        sessionTheme: from_candid_SessionTheme_n48(_uploadFile, _downloadFile, value.sessionTheme),
        trainingType: from_candid_TrainingType_n55(_uploadFile, _downloadFile, value.trainingType),
        rolls: value.rolls
    };
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    blue: null;
} | {
    purple: null;
} | {
    black: null;
} | {
    brown: null;
} | {
    white: null;
}): BeltLevel {
    return "blue" in value ? BeltLevel.blue : "purple" in value ? BeltLevel.purple : "black" in value ? BeltLevel.black : "brown" in value ? BeltLevel.brown : "white" in value ? BeltLevel.white : value;
}
function from_candid_variant_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    openMat: null;
} | {
    takedowns_standup: null;
} | {
    turtleGame: null;
} | {
    transitionsScrambles: null;
} | {
    submissions: null;
} | {
    pinsControl: null;
} | {
    backControl: null;
} | {
    guardRetention: null;
} | {
    escapes: null;
} | {
    sweeps: null;
} | {
    legLocks: null;
} | {
    guardPassing: null;
} | {
    guardSystems: null;
}): SessionTheme {
    return "openMat" in value ? SessionTheme.openMat : "takedowns_standup" in value ? SessionTheme.takedowns_standup : "turtleGame" in value ? SessionTheme.turtleGame : "transitionsScrambles" in value ? SessionTheme.transitionsScrambles : "submissions" in value ? SessionTheme.submissions : "pinsControl" in value ? SessionTheme.pinsControl : "backControl" in value ? SessionTheme.backControl : "guardRetention" in value ? SessionTheme.guardRetention : "escapes" in value ? SessionTheme.escapes : "sweeps" in value ? SessionTheme.sweeps : "legLocks" in value ? SessionTheme.legLocks : "guardPassing" in value ? SessionTheme.guardPassing : "guardSystems" in value ? SessionTheme.guardSystems : value;
}
function from_candid_variant_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    gi: null;
} | {
    noGi: null;
}): TrainingType {
    return "gi" in value ? TrainingType.gi : "noGi" in value ? TrainingType.noGi : value;
}
function from_candid_vec_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CrossTrainingGoal>): Array<CrossTrainingGoal> {
    return value.map((x)=>from_candid_CrossTrainingGoal_n32(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TrainingMilestone>): Array<TrainingMilestone> {
    return value.map((x)=>from_candid_TrainingMilestone_n36(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TrainingGoal>): Array<TrainingGoal> {
    return value.map((x)=>from_candid_TrainingGoal_n42(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BeltProgress>): Array<BeltProgress> {
    return value.map((x)=>from_candid_BeltProgress_n27(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Technique>): Promise<Array<Technique>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Technique_n46(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TrainingSession>): Array<TrainingSession> {
    return value.map((x)=>from_candid_TrainingSession_n53(_uploadFile, _downloadFile, x));
}
function to_candid_BeltLevel_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BeltLevel): _BeltLevel {
    return to_candid_variant_n62(_uploadFile, _downloadFile, value);
}
function to_candid_BeltProgress_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BeltProgress): _BeltProgress {
    return to_candid_record_n60(_uploadFile, _downloadFile, value);
}
function to_candid_Belt_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Belt): _Belt {
    return to_candid_variant_n58(_uploadFile, _downloadFile, value);
}
function to_candid_CrossTrainingGoal_n71(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CrossTrainingGoal): _CrossTrainingGoal {
    return to_candid_record_n72(_uploadFile, _downloadFile, value);
}
async function to_candid_ExtendedProfile_n79(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExtendedProfile): Promise<_ExtendedProfile> {
    return await to_candid_record_n80(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_GymInfo_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GymInfo): _GymInfo {
    return to_candid_record_n66(_uploadFile, _downloadFile, value);
}
function to_candid_SessionTheme_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SessionTheme): _SessionTheme {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
async function to_candid_Technique_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Technique): Promise<_Technique> {
    return await to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_TrainingGoal_n77(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TrainingGoal): _TrainingGoal {
    return to_candid_record_n78(_uploadFile, _downloadFile, value);
}
function to_candid_TrainingMilestone_n74(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TrainingMilestone): _TrainingMilestone {
    return to_candid_record_n75(_uploadFile, _downloadFile, value);
}
function to_candid_TrainingSession_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TrainingSession): _TrainingSession {
    return to_candid_record_n14(_uploadFile, _downloadFile, value);
}
function to_candid_TrainingType_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TrainingType): _TrainingType {
    return to_candid_variant_n16(_uploadFile, _downloadFile, value);
}
async function to_candid_UserProfile_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): Promise<_UserProfile> {
    return await to_candid_record_n69(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_opt_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob | null): Promise<[] | [_ExternalBlob]> {
    return value === null ? candid_none() : candid_some(await to_candid_ExternalBlob_n10(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GymInfo | null): [] | [_GymInfo] {
    return value === null ? candid_none() : candid_some(to_candid_GymInfo_n65(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Time | null): [] | [_Time] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    duration: bigint;
    date: Time;
    moodRating: number;
    sessionTheme: SessionTheme;
    trainingType: TrainingType;
    rolls: bigint;
}): {
    id: string;
    duration: bigint;
    date: _Time;
    moodRating: number;
    sessionTheme: _SessionTheme;
    trainingType: _TrainingType;
    rolls: bigint;
} {
    return {
        id: value.id,
        duration: value.duration,
        date: value.date,
        moodRating: value.moodRating,
        sessionTheme: to_candid_SessionTheme_n11(_uploadFile, _downloadFile, value.sessionTheme),
        trainingType: to_candid_TrainingType_n15(_uploadFile, _downloadFile, value.trainingType),
        rolls: value.rolls
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    belt: BeltLevel;
    imageUrl: string;
    stripes: bigint;
}): {
    belt: _BeltLevel;
    imageUrl: string;
    stripes: bigint;
} {
    return {
        belt: to_candid_BeltLevel_n61(_uploadFile, _downloadFile, value.belt),
        imageUrl: value.imageUrl,
        stripes: value.stripes
    };
}
function to_candid_record_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    logoUrl?: string;
    location: string;
}): {
    name: string;
    logoUrl: [] | [string];
    location: string;
} {
    return {
        name: value.name,
        logoUrl: value.logoUrl ? candid_some(value.logoUrl) : candid_none(),
        location: value.location
    };
}
async function to_candid_record_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio: string;
    gym?: GymInfo;
    beltProgress: BeltProgress;
    nickname: string;
    username: string;
    streakAchievements: Array<StreakAchievement>;
    crossTrainingGoals: Array<CrossTrainingGoal>;
    themePreference: string;
    trainingMilestones: Array<TrainingMilestone>;
    practitionerSince?: Time;
    profilePicture?: ExternalBlob;
    trainingGoals: Array<TrainingGoal>;
}): Promise<{
    bio: string;
    gym: [] | [_GymInfo];
    beltProgress: _BeltProgress;
    nickname: string;
    username: string;
    streakAchievements: Array<_StreakAchievement>;
    crossTrainingGoals: Array<_CrossTrainingGoal>;
    themePreference: string;
    trainingMilestones: Array<_TrainingMilestone>;
    practitionerSince: [] | [_Time];
    profilePicture: [] | [_ExternalBlob];
    trainingGoals: Array<_TrainingGoal>;
}> {
    return {
        bio: value.bio,
        gym: value.gym ? candid_some(to_candid_GymInfo_n65(_uploadFile, _downloadFile, value.gym)) : candid_none(),
        beltProgress: to_candid_BeltProgress_n59(_uploadFile, _downloadFile, value.beltProgress),
        nickname: value.nickname,
        username: value.username,
        streakAchievements: value.streakAchievements,
        crossTrainingGoals: to_candid_vec_n70(_uploadFile, _downloadFile, value.crossTrainingGoals),
        themePreference: value.themePreference,
        trainingMilestones: to_candid_vec_n73(_uploadFile, _downloadFile, value.trainingMilestones),
        practitionerSince: value.practitionerSince ? candid_some(value.practitionerSince) : candid_none(),
        profilePicture: value.profilePicture ? candid_some(await to_candid_ExternalBlob_n10(_uploadFile, _downloadFile, value.profilePicture)) : candid_none(),
        trainingGoals: to_candid_vec_n76(_uploadFile, _downloadFile, value.trainingGoals)
    };
}
function to_candid_record_n72(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    completionDate?: Time;
    name: string;
    description: string;
    progress: bigint;
    targetArea: string;
}): {
    id: string;
    completionDate: [] | [_Time];
    name: string;
    description: string;
    progress: bigint;
    targetArea: string;
} {
    return {
        id: value.id,
        completionDate: value.completionDate ? candid_some(value.completionDate) : candid_none(),
        name: value.name,
        description: value.description,
        progress: value.progress,
        targetArea: value.targetArea
    };
}
function to_candid_record_n75(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    beltProgress?: BeltProgress;
    achievedDate: Time;
    name: string;
    description: string;
}): {
    id: string;
    beltProgress: [] | [_BeltProgress];
    achievedDate: _Time;
    name: string;
    description: string;
} {
    return {
        id: value.id,
        beltProgress: value.beltProgress ? candid_some(to_candid_BeltProgress_n59(_uploadFile, _downloadFile, value.beltProgress)) : candid_none(),
        achievedDate: value.achievedDate,
        name: value.name,
        description: value.description
    };
}
function to_candid_record_n78(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    completedRepetitions: bigint;
    name: string;
    description: string;
    deadline?: Time;
    creationDate: Time;
    targetRepetitions: bigint;
}): {
    id: string;
    completedRepetitions: bigint;
    name: string;
    description: string;
    deadline: [] | [_Time];
    creationDate: _Time;
    targetRepetitions: bigint;
} {
    return {
        id: value.id,
        completedRepetitions: value.completedRepetitions,
        name: value.name,
        description: value.description,
        deadline: value.deadline ? candid_some(value.deadline) : candid_none(),
        creationDate: value.creationDate,
        targetRepetitions: value.targetRepetitions
    };
}
async function to_candid_record_n80(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio: string;
    gym?: GymInfo;
    beltProgress: BeltProgress;
    nickname: string;
    username: string;
    streakAchievements: Array<StreakAchievement>;
    crossTrainingGoals: Array<CrossTrainingGoal>;
    trainingMilestones: Array<TrainingMilestone>;
    practitionerSince?: Time;
    profilePicture?: ExternalBlob;
    trainingGoals: Array<TrainingGoal>;
}): Promise<{
    bio: string;
    gym: [] | [_GymInfo];
    beltProgress: _BeltProgress;
    nickname: string;
    username: string;
    streakAchievements: Array<_StreakAchievement>;
    crossTrainingGoals: Array<_CrossTrainingGoal>;
    trainingMilestones: Array<_TrainingMilestone>;
    practitionerSince: [] | [_Time];
    profilePicture: [] | [_ExternalBlob];
    trainingGoals: Array<_TrainingGoal>;
}> {
    return {
        bio: value.bio,
        gym: value.gym ? candid_some(to_candid_GymInfo_n65(_uploadFile, _downloadFile, value.gym)) : candid_none(),
        beltProgress: to_candid_BeltProgress_n59(_uploadFile, _downloadFile, value.beltProgress),
        nickname: value.nickname,
        username: value.username,
        streakAchievements: value.streakAchievements,
        crossTrainingGoals: to_candid_vec_n70(_uploadFile, _downloadFile, value.crossTrainingGoals),
        trainingMilestones: to_candid_vec_n73(_uploadFile, _downloadFile, value.trainingMilestones),
        practitionerSince: value.practitionerSince ? candid_some(value.practitionerSince) : candid_none(),
        profilePicture: value.profilePicture ? candid_some(await to_candid_ExternalBlob_n10(_uploadFile, _downloadFile, value.profilePicture)) : candid_none(),
        trainingGoals: to_candid_vec_n76(_uploadFile, _downloadFile, value.trainingGoals)
    };
}
async function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    typ: string;
    thumbnail?: ExternalBlob;
    link: string;
    name: string;
    tags: Array<string>;
    description: string;
    linkedSessions: Array<string>;
    category: SessionTheme;
}): Promise<{
    id: string;
    typ: string;
    thumbnail: [] | [_ExternalBlob];
    link: string;
    name: string;
    tags: Array<string>;
    description: string;
    linkedSessions: Array<string>;
    category: _SessionTheme;
}> {
    return {
        id: value.id,
        typ: value.typ,
        thumbnail: value.thumbnail ? candid_some(await to_candid_ExternalBlob_n10(_uploadFile, _downloadFile, value.thumbnail)) : candid_none(),
        link: value.link,
        name: value.name,
        tags: value.tags,
        description: value.description,
        linkedSessions: value.linkedSessions,
        category: to_candid_SessionTheme_n11(_uploadFile, _downloadFile, value.category)
    };
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SessionTheme): {
    openMat: null;
} | {
    takedowns_standup: null;
} | {
    turtleGame: null;
} | {
    transitionsScrambles: null;
} | {
    submissions: null;
} | {
    pinsControl: null;
} | {
    backControl: null;
} | {
    guardRetention: null;
} | {
    escapes: null;
} | {
    sweeps: null;
} | {
    legLocks: null;
} | {
    guardPassing: null;
} | {
    guardSystems: null;
} {
    return value == SessionTheme.openMat ? {
        openMat: null
    } : value == SessionTheme.takedowns_standup ? {
        takedowns_standup: null
    } : value == SessionTheme.turtleGame ? {
        turtleGame: null
    } : value == SessionTheme.transitionsScrambles ? {
        transitionsScrambles: null
    } : value == SessionTheme.submissions ? {
        submissions: null
    } : value == SessionTheme.pinsControl ? {
        pinsControl: null
    } : value == SessionTheme.backControl ? {
        backControl: null
    } : value == SessionTheme.guardRetention ? {
        guardRetention: null
    } : value == SessionTheme.escapes ? {
        escapes: null
    } : value == SessionTheme.sweeps ? {
        sweeps: null
    } : value == SessionTheme.legLocks ? {
        legLocks: null
    } : value == SessionTheme.guardPassing ? {
        guardPassing: null
    } : value == SessionTheme.guardSystems ? {
        guardSystems: null
    } : value;
}
function to_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TrainingType): {
    gi: null;
} | {
    noGi: null;
} {
    return value == TrainingType.gi ? {
        gi: null
    } : value == TrainingType.noGi ? {
        noGi: null
    } : value;
}
function to_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Belt): {
    blue: null;
} | {
    purple: null;
} | {
    black: null;
} | {
    brown: null;
} {
    return value == Belt.blue ? {
        blue: null
    } : value == Belt.purple ? {
        purple: null
    } : value == Belt.black ? {
        black: null
    } : value == Belt.brown ? {
        brown: null
    } : value;
}
function to_candid_variant_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BeltLevel): {
    blue: null;
} | {
    purple: null;
} | {
    black: null;
} | {
    brown: null;
} | {
    white: null;
} {
    return value == BeltLevel.blue ? {
        blue: null
    } : value == BeltLevel.purple ? {
        purple: null
    } : value == BeltLevel.black ? {
        black: null
    } : value == BeltLevel.brown ? {
        brown: null
    } : value == BeltLevel.white ? {
        white: null
    } : value;
}
function to_candid_vec_n70(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<CrossTrainingGoal>): Array<_CrossTrainingGoal> {
    return value.map((x)=>to_candid_CrossTrainingGoal_n71(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n73(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<TrainingMilestone>): Array<_TrainingMilestone> {
    return value.map((x)=>to_candid_TrainingMilestone_n74(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n76(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<TrainingGoal>): Array<_TrainingGoal> {
    return value.map((x)=>to_candid_TrainingGoal_n77(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n81(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<TrainingSession>): Array<_TrainingSession> {
    return value.map((x)=>to_candid_TrainingSession_n13(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
